"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { useGoal } from "@/hooks/use-goal";
import { getWeekStart, toDateString } from "@/lib/date-utils";

const STORAGE_KEY = "weeklyPlanPrompted";

/** 本地 YYYY-MM-DD。注意：toDateString 基于 UTC（东八区会得到前一天），
 *  而 URL ?week= 需要本地周一日期，两者语义不同，必须分开用。 */
function toLocalDate(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

/**
 * 周计划到期提醒 — 周日登录时检测"下周无计划"，提示生成下周计划。
 * 挂载在 (authenticated)/layout.tsx，全局生效（不只限任务页）。
 * 防打扰：localStorage 记录已提示的下周一日期，每周仅弹一次。
 */
export function WeeklyPlanReminder() {
  const router = useRouter();
  const { data: goal } = useGoal();
  const [show, setShow] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState<{ count: number; weekNav: string } | null>(null);
  const [nextMonday, setNextMonday] = useState("");
  const checkedRef = useRef(false);

  useEffect(() => {
    // 只检查一次；无目标不打扰
    if (checkedRef.current || show || autoGenerated) return;
    if (!goal) return; // undefined=加载中, null=未设目标 → 都跳过

    const today = new Date();
    if (today.getDay() !== 0) {
      checkedRef.current = true;
      return; // 非周日
    }

    // 下周周一
    const nm = new Date(getWeekStart(today));
    nm.setDate(nm.getDate() + 7);
    const nmNav = toLocalDate(nm); // 本地周一 → 用于 /tasks?week= 导航 + 防打扰 key
    const nmCheck = toDateString(nm); // 周一的 UTC 日期 → 用于 /api/tasks?weekStart=（与 generate-plan 存储/查询语义一致）
    setNextMonday(nmNav);

    // 本周已提示过 → 跳过
    try {
      if (localStorage.getItem(STORAGE_KEY) === nmNav) {
        checkedRef.current = true;
        return;
      }
    } catch {
      /* ignore */
    }

    // 下周是否已有计划
    Promise.all([
      fetch(`/api/tasks?weekStart=${nmCheck}`).then((res) => res.json()),
      fetch(`/api/weekly-plans?weekStart=${nmNav}`).then((res) => res.json()),
    ])
      .then(async ([taskData, planData]) => {
        if ((taskData.tasks || []).length > 0 || planData.draft || planData.active) {
          checkedRef.current = true;
          return; // 下周已有计划
        }

        // 读取驾驶模式（服务端直读）
        let mode = "assisted";
        try {
          const sRes = await fetch("/api/user/settings");
          const sData = await sRes.json();
          mode = sData.drivingMode || "assisted";
        } catch {
          /* ignore */
        }

        if (mode === "auto") {
          // 自动驾驶只负责提前生成草稿；仍需用户查看并确认后才写入正式任务。
          try {
            const gRes = await fetch("/api/ai/generate-plan", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ startDate: nmCheck }),
            });
            const gData = await gRes.json();
            checkedRef.current = true;
            if (gRes.ok && Array.isArray(gData.tasks) && gData.tasks.length > 0) {
              try {
                localStorage.setItem(STORAGE_KEY, nmNav);
              } catch {
                /* ignore */
              }
              setAutoGenerated({ count: gData.tasks.length, weekNav: nmNav });
            } else {
              setShow(true); // 生成失败 → 退回温和询问
            }
          } catch {
            checkedRef.current = true;
            setShow(true);
          }
        } else {
          checkedRef.current = true;
          setShow(true); // 辅助/手动 → 询问
        }
      })
      .catch(() => {
        checkedRef.current = true;
      });
  }, [goal, show, autoGenerated]);

  const handleGenerate = () => {
    try {
      localStorage.setItem(STORAGE_KEY, nextMonday);
    } catch {
      /* ignore */
    }
    router.push(`/tasks?week=${nextMonday}&generate=1`);
  };

  const handleDismiss = () => {
    try {
      localStorage.setItem(STORAGE_KEY, nextMonday);
    } catch {
      /* ignore */
    }
    setShow(false);
  };

  if (!show && !autoGenerated) return null;

  if (show) {
    return (
      <Modal
        open
        onClose={handleDismiss}
        size="sm"
        title={
          <span className="flex items-center gap-3">
            <span className="text-2xl leading-none">📅</span>
            <span>本周告一段落</span>
          </span>
        }
        description="下周计划还没生成。不着急，等你想排的时候，点一下就能让 AI 排好，之后随时能改。"
        footer={
          <>
            <Button variant="outline" className="flex-1" onClick={handleDismiss}>
              下次再说
            </Button>
            <Button className="flex-1" onClick={handleGenerate}>
              生成下周计划
            </Button>
          </>
        }
      />
    );
  }

  return (
    <Modal
      open
      onClose={() => setAutoGenerated(null)}
      size="sm"
      title={
        <span className="flex items-center gap-3">
          <span className="text-2xl leading-none">✨</span>
          <span>下周计划已自动生成</span>
        </span>
      }
      description={`自动驾驶模式已为你生成下周的 ${autoGenerated?.count} 个学习任务草稿。这只是草稿，你随时可以在任务页调整或删改。`}
      footer={
        <>
          <Button variant="outline" className="flex-1" onClick={() => setAutoGenerated(null)}>
            知道了
          </Button>
          <Button className="flex-1" onClick={() => router.push(`/tasks?week=${autoGenerated?.weekNav}`)}>
            去看看
          </Button>
        </>
      }
    />
  );
}
